
export default {
    REQUEST_START: 'REQUEST_START',
    REQUEST_END: 'REQUEST_END',
    SET_RESPONSE_NUMBER_WORDS: 'SET_RESPONSE_NUMBER_WORDS',
    SET_API_ERROR_RESPONSE: 'SET_API_ERROR_RESPONSE'
}